'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option or rebuild the Visual Studio project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "15.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class MainResource
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Resources.MainResource", Global.System.Reflection.[Assembly].Load("App_GlobalResources"))
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Adresa.
        '''</summary>
        Friend Shared ReadOnly Property Adresa() As String
            Get
                Return ResourceManager.GetString("Adresa", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Obavijest.
        '''</summary>
        Friend Shared ReadOnly Property AlertNotificationNaslov() As String
            Get
                Return ResourceManager.GetString("AlertNotificationNaslov", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Upozorenje!.
        '''</summary>
        Friend Shared ReadOnly Property AlertWarningNaslov() As String
            Get
                Return ResourceManager.GetString("AlertWarningNaslov", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Dodaj.
        '''</summary>
        Friend Shared ReadOnly Property btnDodaj() As String
            Get
                Return ResourceManager.GetString("btnDodaj", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ispis.
        '''</summary>
        Friend Shared ReadOnly Property btnIspis() As String
            Get
                Return ResourceManager.GetString("btnIspis", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Novi unos.
        '''</summary>
        Friend Shared ReadOnly Property btnNew() As String
            Get
                Return ResourceManager.GetString("btnNew", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Obriši.
        '''</summary>
        Friend Shared ReadOnly Property BtnObrisi() As String
            Get
                Return ResourceManager.GetString("BtnObrisi", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Odustani.
        '''</summary>
        Friend Shared ReadOnly Property BtnOdustani() As String
            Get
                Return ResourceManager.GetString("BtnOdustani", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to U redu.
        '''</summary>
        Friend Shared ReadOnly Property btnOk() As String
            Get
                Return ResourceManager.GetString("btnOk", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Pretraži.
        '''</summary>
        Friend Shared ReadOnly Property btnSearch() As String
            Get
                Return ResourceManager.GetString("btnSearch", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Pretraži sve.
        '''</summary>
        Friend Shared ReadOnly Property btnSearchAll() As String
            Get
                Return ResourceManager.GetString("btnSearchAll", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Spremi.
        '''</summary>
        Friend Shared ReadOnly Property BtnSpremi() As String
            Get
                Return ResourceManager.GetString("BtnSpremi", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Spremi promjene.
        '''</summary>
        Friend Shared ReadOnly Property BtnUpdate() As String
            Get
                Return ResourceManager.GetString("BtnUpdate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Uredi.
        '''</summary>
        Friend Shared ReadOnly Property btnUredi() As String
            Get
                Return ResourceManager.GetString("btnUredi", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Zaduži.
        '''</summary>
        Friend Shared ReadOnly Property btnZaduzi() As String
            Get
                Return ResourceManager.GetString("btnZaduzi", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Zbroji.
        '''</summary>
        Friend Shared ReadOnly Property btnZbroji() As String
            Get
                Return ResourceManager.GetString("btnZbroji", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Potvrda.
        '''</summary>
        Friend Shared ReadOnly Property ConfirmDeleteNaslov() As String
            Get
                Return ResourceManager.GetString("ConfirmDeleteNaslov", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Datum.
        '''</summary>
        Friend Shared ReadOnly Property Datum() As String
            Get
                Return ResourceManager.GetString("Datum", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Datum statusa.
        '''</summary>
        Friend Shared ReadOnly Property DatumStatus() As String
            Get
                Return ResourceManager.GetString("DatumStatus", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Datum unosa.
        '''</summary>
        Friend Shared ReadOnly Property DatumUnosa() As String
            Get
                Return ResourceManager.GetString("DatumUnosa", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to E-mail.
        '''</summary>
        Friend Shared ReadOnly Property Email() As String
            Get
                Return ResourceManager.GetString("Email", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Odaberite parametre za pretraživanje / podaci ne postoje.
        '''</summary>
        Friend Shared ReadOnly Property EmptyData() As String
            Get
                Return ResourceManager.GetString("EmptyData", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ev. oznaka.
        '''</summary>
        Friend Shared ReadOnly Property EvOznaka() As String
            Get
                Return ResourceManager.GetString("EvOznaka", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to HR.
        '''</summary>
        Friend Shared ReadOnly Property FarmaSifraPrefix() As String
            Get
                Return ResourceManager.GetString("FarmaSifraPrefix", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Godina.
        '''</summary>
        Friend Shared ReadOnly Property Godina() As String
            Get
                Return ResourceManager.GetString("Godina", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Došlo je do greške, molim pokušajte ponovo..
        '''</summary>
        Friend Shared ReadOnly Property GreskaOpcenito() As String
            Get
                Return ResourceManager.GetString("GreskaOpcenito", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Id.
        '''</summary>
        Friend Shared ReadOnly Property Id() As String
            Get
                Return ResourceManager.GetString("Id", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to IKG.
        '''</summary>
        Friend Shared ReadOnly Property Ikg() As String
            Get
                Return ResourceManager.GetString("Ikg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ime.
        '''</summary>
        Friend Shared ReadOnly Property Ime() As String
            Get
                Return ResourceManager.GetString("Ime", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to  - Izaberi ovlaštenu vet. organizaciju - .
        '''</summary>
        Friend Shared ReadOnly Property IzaberiVetOrganizaciju() As String
            Get
                Return ResourceManager.GetString("IzaberiVetOrganizaciju", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to  - Izaberi županiju - .
        '''</summary>
        Friend Shared ReadOnly Property IzaberiZupaniju() As String
            Get
                Return ResourceManager.GetString("IzaberiZupaniju", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to JIBG.
        '''</summary>
        Friend Shared ReadOnly Property Jibg() As String
            Get
                Return ResourceManager.GetString("Jibg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Jop.
        '''</summary>
        Friend Shared ReadOnly Property Jop() As String
            Get
                Return ResourceManager.GetString("Jop", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Kućni broj.
        '''</summary>
        Friend Shared ReadOnly Property Kbr() As String
            Get
                Return ResourceManager.GetString("Kbr", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Klasa.
        '''</summary>
        Friend Shared ReadOnly Property Klasa() As String
            Get
                Return ResourceManager.GetString("Klasa", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Korisnik nije logiran.
        '''</summary>
        Friend Shared ReadOnly Property KorisnikNijeLogiran() As String
            Get
                Return ResourceManager.GetString("KorisnikNijeLogiran", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to MIBPG.
        '''</summary>
        Friend Shared ReadOnly Property Mibpg() As String
            Get
                Return ResourceManager.GetString("Mibpg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Mobitel.
        '''</summary>
        Friend Shared ReadOnly Property Mobitel() As String
            Get
                Return ResourceManager.GetString("Mobitel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Podatak mora biti broj.
        '''</summary>
        Friend Shared ReadOnly Property MoraBitiBroj() As String
            Get
                Return ResourceManager.GetString("MoraBitiBroj", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Naselje.
        '''</summary>
        Friend Shared ReadOnly Property Naselje() As String
            Get
                Return ResourceManager.GetString("Naselje", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Veti2Connect.
        '''</summary>
        Friend Shared ReadOnly Property Naslov() As String
            Get
                Return ResourceManager.GetString("Naslov", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Naziv.
        '''</summary>
        Friend Shared ReadOnly Property Naziv() As String
            Get
                Return ResourceManager.GetString("Naziv", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Odjava.
        '''</summary>
        Friend Shared ReadOnly Property Odjava() As String
            Get
                Return ResourceManager.GetString("Odjava", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to OIB.
        '''</summary>
        Friend Shared ReadOnly Property Oib() As String
            Get
                Return ResourceManager.GetString("Oib", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Oib je neispravan, molim ispravite oib..
        '''</summary>
        Friend Shared ReadOnly Property OibNeispravan() As String
            Get
                Return ResourceManager.GetString("OibNeispravan", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Općina.
        '''</summary>
        Friend Shared ReadOnly Property Opcina() As String
            Get
                Return ResourceManager.GetString("Opcina", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Organizacija.
        '''</summary>
        Friend Shared ReadOnly Property Organizacija() As String
            Get
                Return ResourceManager.GetString("Organizacija", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Vrsta pretrage.
        '''</summary>
        Friend Shared ReadOnly Property PanelVrstaPretrageTitle() As String
            Get
                Return ResourceManager.GetString("PanelVrstaPretrageTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Lozinka.
        '''</summary>
        Friend Shared ReadOnly Property Password() As String
            Get
                Return ResourceManager.GetString("Password", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Poštanski broj.
        '''</summary>
        Friend Shared ReadOnly Property Pbr() As String
            Get
                Return ResourceManager.GetString("Pbr", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Jeste li sigurni da želite ažurirati zapis?.
        '''</summary>
        Friend Shared ReadOnly Property PitanjeZaAzuriranjeOpcenito() As String
            Get
                Return ResourceManager.GetString("PitanjeZaAzuriranjeOpcenito", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Jeste li sigurni da želite obrisati zapis?.
        '''</summary>
        Friend Shared ReadOnly Property PitanjeZaBrisanjeOpcenito() As String
            Get
                Return ResourceManager.GetString("PitanjeZaBrisanjeOpcenito", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to .
        '''</summary>
        Friend Shared ReadOnly Property Podnaslov() As String
            Get
                Return ResourceManager.GetString("Podnaslov", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Područje.
        '''</summary>
        Friend Shared ReadOnly Property Podrucje() As String
            Get
                Return ResourceManager.GetString("Podrucje", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Pošta.
        '''</summary>
        Friend Shared ReadOnly Property Posta() As String
            Get
                Return ResourceManager.GetString("Posta", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Zapis je uspješno obrisan..
        '''</summary>
        Friend Shared ReadOnly Property PotvrdaBrisanja() As String
            Get
                Return ResourceManager.GetString("PotvrdaBrisanja", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Zapis je uspješno izmjenjen..
        '''</summary>
        Friend Shared ReadOnly Property PotvrdaPromjene() As String
            Get
                Return ResourceManager.GetString("PotvrdaPromjene", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Zapis je uspješno spremljen..
        '''</summary>
        Friend Shared ReadOnly Property PotvrdaSpremanja() As String
            Get
                Return ResourceManager.GetString("PotvrdaSpremanja", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Prezime.
        '''</summary>
        Friend Shared ReadOnly Property Prezime() As String
            Get
                Return ResourceManager.GetString("Prezime", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Prijava.
        '''</summary>
        Friend Shared ReadOnly Property Prijava() As String
            Get
                Return ResourceManager.GetString("Prijava", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;span style=&apos;display:block;&apos; class=&apos;alert alert-danger&apos;&gt;Vaš pokušaj prijave nije uspio.&lt;/span&gt;.
        '''</summary>
        Friend Shared ReadOnly Property PrijavaGreska() As String
            Get
                Return ResourceManager.GetString("PrijavaGreska", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Prikaz.
        '''</summary>
        Friend Shared ReadOnly Property Prikaz() As String
            Get
                Return ResourceManager.GetString("Prikaz", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Radno mjesto.
        '''</summary>
        Friend Shared ReadOnly Property RadnoMjesto() As String
            Get
                Return ResourceManager.GetString("RadnoMjesto", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Status.
        '''</summary>
        Friend Shared ReadOnly Property Status() As String
            Get
                Return ResourceManager.GetString("Status", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Telefonski broj.
        '''</summary>
        Friend Shared ReadOnly Property TelBroj() As String
            Get
                Return ResourceManager.GetString("TelBroj", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Telefon .
        '''</summary>
        Friend Shared ReadOnly Property Telefon() As String
            Get
                Return ResourceManager.GetString("Telefon", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ukupno.
        '''</summary>
        Friend Shared ReadOnly Property Ukupno() As String
            Get
                Return ResourceManager.GetString("Ukupno", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ulica.
        '''</summary>
        Friend Shared ReadOnly Property Ulica() As String
            Get
                Return ResourceManager.GetString("Ulica", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Uloga.
        '''</summary>
        Friend Shared ReadOnly Property Uloga() As String
            Get
                Return ResourceManager.GetString("Uloga", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ur. broj.
        '''</summary>
        Friend Shared ReadOnly Property Urbr() As String
            Get
                Return ResourceManager.GetString("Urbr", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Korisničko ime.
        '''</summary>
        Friend Shared ReadOnly Property Username() As String
            Get
                Return ResourceManager.GetString("Username", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Zatvori.
        '''</summary>
        Friend Shared ReadOnly Property Zatvori() As String
            Get
                Return ResourceManager.GetString("Zatvori", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Županija.
        '''</summary>
        Friend Shared ReadOnly Property Zupanija() As String
            Get
                Return ResourceManager.GetString("Zupanija", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
